# Generated by Django 5.1.6 on 2025-05-14 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponenteCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('area', models.CharField(choices=[('LINGUAGENS', 'Linguagens e suas Tecnologias'), ('MATEMATICA', 'Matemática e suas Tecnologias'), ('NATUREZA', 'Ciências da Natureza e suas Tecnologias'), ('HUMANAS', 'Ciências Humanas e Sociais Aplicadas'), ('TECNICO', 'Formação Técnica e Profissional')], max_length=20)),
                ('tipo', models.CharField(choices=[('BNCC', 'Base Nacional Comum Curricular'), ('ITINERARIO', 'Itinerário Formativo')], max_length=20)),
                ('carga_horaria', models.IntegerField(help_text='Carga horária em horas')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instituicao')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(choices=[('1', '1ª Série'), ('2', '2ª Série'), ('3', '3ª Série')], max_length=1)),
                ('ano_letivo', models.IntegerField()),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instituicao')),
            ],
            options={
                'unique_together': {('instituicao', 'ano', 'ano_letivo')},
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('turno', models.CharField(max_length=20)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.serie')),
            ],
        ),
        migrations.CreateModel(
            name='MatriculaDiscente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField(auto_now_add=True)),
                ('discente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.discente')),
                ('itinerarios_escolhidos', models.ManyToManyField(limit_choices_to={'tipo': 'ITINERARIO'}, related_name='matriculas', to='core.componentecurricular')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.turma')),
            ],
            options={
                'unique_together': {('discente', 'turma')},
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.docente')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.componentecurricular')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.turma')),
            ],
            options={
                'unique_together': {('componente', 'turma', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
